export type TipoRegistro = 'ingreso' | 'gasto'
export type EstadoRegistro = 'pendiente' | 'pagado'
export type TipoDocumento = 'factura' | 'boleta' | 'nota_credito' | 'nota_debito' | 'liquidacion' | 'sin_documento'
export type TipoGasto = 'factura_proveedor' | 'salario' | 'arriendo' | 'subscripcion' | 'otro'
export type FuenteRegistro = 'manual' | 'sumup'
